services:
  # Aggregator
  aggregator:
    hostname: aggregator
    build: ./aggregator
    restart: unless-stopped
    logging:
      options:
        max-size: 2m
        max-file: "3"
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - PGHOST=database
      - PGUSER=anon
      - PGPASSWORD=admin
      - PGDATABASE=anon
      - PGPORT=5432
    ports:
      - "80:80"
    volumes:
      - './shared:/usr/bin/aggregator/downloads'
    # profiles:
    #   - donotstart

  # Automail
  automail:
    build: ./automail
    restart: unless-stopped
    logging:
      options:
        max-size: 2m
        max-file: "3"
    environment:
      - LOGLEVEL=${LOGLEVEL:-debug}
    volumes:
      - './shared:/usr/bin/automail/downloads'
    # profiles:
    #   - donotstart

  # Database
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-anon@localhost.net}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_SERVER_JSON_FILE=${PGADMIN_SERVER_JSON_FILE}
    ports:
      - "81:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - database
    # profiles:
    #   - donotstart

  database:
    hostname: database
    build: ./database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-anon}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
    logging:
      options:
        max-size: 2m
        max-file: "3"
    ports:
      - "${DB_PORT:-5432}:5432"
    # profiles:
    #   - donotstart

volumes:
  shared: