services:
  # Automail
  automail:
    build: ./automail
    restart: unless-stopped
    logging:
      options:
        max-size: 2m
        max-file: "3"
    environment:
      - LOGLEVEL=${LOGLEVEL:-debug}
    volumes:
      - './shared:/usr/bin/automail/downloads'
    profiles:
      - donotstart

  # Database
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-anon@localhost.net}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_SERVER_JSON_FILE=${PGADMIN_SERVER_JSON_FILE}
    ports:
      - "81:80"
    depends_on:
      - database
    # profiles:
    #   - donotstart

  database:
    build: ./database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-anon}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
    logging:
      options:
        max-size: 2m
        max-file: "3"
    ports:
      - "${DB_PORT:-5432}:5432"
    # profiles:
    #   - donotstart

volumes:
  shared: